apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment-service
  template:
    metadata:
      labels:
        app: appointment-service
    spec:
      containers:
      - name: appointment-service
        image: kaushiks93/appointment_service_app:latest
        imagePullPolicy: IfNotPresent
        envFrom:
          - secretRef:
              name: appointment-app-env
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: appointment-service
spec:
  selector:
    app: appointment-service
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8000
  type: LoadBalancer
