# Generated by Django 5.1.3 on 2024-12-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_remove_prescription_dosage'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='appointment_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
