# Generated by Django 5.1.3 on 2024-12-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_prescription_appointment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='appointment_id',
            field=models.IntegerField(unique=True),
        ),
    ]
