apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment-service
  template:
    metadata:
      labels:
        app: appointment-service
    spec:
      containers:
      - name: appointment-service
        image: appointment-service-app:latest
        imagePullPolicy: IfNotPresent
        envFrom:
          - secretRef:
              name: appointment-app-env
        ports:
        - containerPort: 8000
