name: Appointment Service Build and Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t kaushiks93/appointment-service-app:latest .
          docker push kaushiks93/appointment-service-app:latest

      # - name: Set up gcloud CLI
      #   uses: google-github-actions/setup-gcloud@v1
      #   with:
      #     service_account_key: ${{ secrets.GCLOUD_KEY }}
      #     project_id: <your-project-id>

      # - name: Authenticate with GKE
      #   run: |
      #     gcloud container clusters get-credentials django-cluster --region=us-central1

      # - name: Deploy to GKE
      #   run: |
      #     kubectl apply -f k8s-deployment.yaml
