# Generated by Django 5.1.3 on 2024-11-28 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='contact_info',
            new_name='contact_number',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='contact_info',
            new_name='contact_number',
        ),
    ]
