# Generated by Django 5.1.3 on 2024-11-28 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_rename_contact_info_doctor_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='availability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='records.availability', unique=True),
        ),
    ]
