apiVersion: v1
kind: Service
metadata:
  name: patient-consumer
spec:
  selector:
    app: patient-consumer
    type: ClusterIP
  # ports:
  #   - protocol: TCP
  #     port: 80
  #     targetPort: 80
